name: Kaggle Badges

on:
  schedule:
    - cron: "11 11 1 * *" # 11:11 AM on the 1st of every month
  workflow_dispatch:
  push:
    branches:
      - main   # your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Puppeteer browser
        run: npx puppeteer browsers install chrome

      - name: Use Kaggle Badges Action
        uses: spider-man-tm/kaggle-badges@v0.1.0
        with:
          user_name: { hakonem }
       
      - name: Commit and Push SVG files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./kaggle-badges/*
          git commit -m "Add generated SVG files" || echo "No changes to commit"
          git push
