name: Update badges

on:
  schedule:
    # Runs at 0am UTC every day
    - cron: "0 0 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@2.3.0
        with:
    # GitHub access token with Repo scope
    GH_TOKEN: # default is ${{ github.token }}
    # Your GitHub repository
    REPOSITORY: # optional, default is ${{ github.repository }}
    # Add a commit message of your choice
    COMMIT_MESSAGE: # optional, default is Updated README with new badges
    # User name used in Credly
    CREDLY_USER: emma-louise-hakonsen
    # The sort type for return credly badges [RECENT/POPULAR]
    CREDLY_SORT: # optional, default is RECENT
    # Defines the badge dimension.
    BADGE_SIZE: # optional, default is 110
    # the number of the last badges that need to show - (0 to not set limit)
    NUMBER_LAST_BADGES: # optional, default is 0
